# Default values for ssh-bastion.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

sshConfig:
  authorizedKeys: {}
    # alcides: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjYENeor3OYyPxxz4wac7trH6NUkhOufFhZ5X6E2OajF0lEGKwMlT1FoCLtrkyHUKtuyHpr0SGNChebmdBKJmFTUcPWMLCqMLXXDXwNE//G5HpYnDqWxUqEJ6uXbRJldoztWkCBxaExSEqPRtrEZ7m8dvtb2WqA4CdOBIAzvODzUwADz3o+t1fzVcdB5nFiblqmFHinBqgxK4azF1ucnytW2WS5u10Lpwb02nOs8peOZ261UvYsjkZ9MSCSpSVecEg5kHN7iBxIdSUn+yg/yLnJdhh0nF2/+LczlD1dVGJbaHSAb3N2GjMG+BKDa1AxH8JAIwkOLYMvnFIO8IhuUzV

image:
  repository: ubuntu
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 22.04

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: LoadBalancer
  port: 22

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

hostKeys:
  autoGenerate: true
  ssh_host_dsa_key: ""
  ssh_host_dsa_key_pub: ""
  ssh_host_ecdsa_key: ""
  ssh_host_ecdsa_key_pub: ""
  ssh_host_ed25519_key: ""
  ssh_host_ed25519_key_pub: ""
  ssh_host_rsa_key: ""
  ssh_host_rsa_key_pub: ""
