apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssh-bastion.fullname" . }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- include "ssh-bastion.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ssh-bastion.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- include "ssh-bastion.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssh-bastion.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: ssh-bastion
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            {{- /* This is necessary for triggering rollout of pods when changing keys */}}
            - name: DEPLOYMENT_ROLLOUT
              value: "{{ .Values.sshConfig.authorizedKeys | toYaml | b64enc | sha1sum}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 22
          volumeMounts:
            {{- if not .Values.hostKeys.autoGenerate }}
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_ecdsa_key
              subPath: "ssh_host_ecdsa_key"
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_ecdsa_key.pub
              subPath: "ssh_host_ecdsa_key.pub"
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_ed25519_key
              subPath: "ssh_host_ed25519_key"
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_ed25519_key.pub
              subPath: "ssh_host_ed25519_key.pub"
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_rsa_key
              subPath: "ssh_host_rsa_key"
            - name: host-keys
              mountPath: /etc/ssh/ssh_host_rsa_key.pub
              subPath: "ssh_host_rsa_key.pub"
            {{- end }}
            - name: ssh-config
              mountPath: /etc/ssh/keys
              subPath: keys
            - name: ssh-config
              mountPath: /etc/ssh/ssh-config.sh
              subPath: ssh-config.sh
            - name: ssh-config
              mountPath: /etc/ssh/sshd_config
              subPath: sshd_config
          command:
            - bash
            - /etc/ssh/ssh-config.sh
      volumes:
        {{- if not .Values.hostKeys.autoGenerate }}
        - name: host-keys
          secret:
            secretName: {{ include "ssh-bastion.fullname" . }}-secret
            defaultMode: 0400
        {{- end }}
        - name: ssh-config
          configMap:
            name: ssh-config-configmap
