{{ if not .Values.hostKeys.autoGenerate }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ssh-bastion.fullname" . }}-secret
  labels:
    {{- include "ssh-bastion.labels" . | nindent 4 }}
type: Opaque
data:
  ssh_host_dsa_key: {{ .Values.hostKeys.ssh_host_dsa_key | b64enc }}
  ssh_host_dsa_key.pub: {{ .Values.hostKeys.ssh_host_dsa_key_pub | b64enc }}
  ssh_host_ecdsa_key: {{ .Values.hostKeys.ssh_host_ecdsa_key | b64enc }}
  ssh_host_ecdsa_key.pub: {{ .Values.hostKeys.ssh_host_ecdsa_key_pub | b64enc }}
  ssh_host_ed25519_key: {{ .Values.hostKeys.ssh_host_ed25519_key | b64enc }}
  ssh_host_ed25519_key.pub: {{ .Values.hostKeys.ssh_host_ed25519_key_pub | b64enc }}
  ssh_host_rsa_key: {{ .Values.hostKeys.ssh_host_rsa_key | b64enc }}
  ssh_host_rsa_key.pub: {{ .Values.hostKeys.ssh_host_rsa_key_pub | b64enc }}
{{ end }}